# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Nodejs.gitlab-ci.yml

# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

before_script:
  - export DEBIAN_FRONTEND="noninteractive"
  # curl librsvg2-dev libssl-dev wget
  - apt-get update -qq -o Dpkg::Use-Pty=0
  - apt-get install -y apt-utils -qq -o Dpkg::Use-Pty=0
  - apt-get upgrade -y -qq -o Dpkg::Use-Pty=0
  - apt-get install -y libwebkit2gtk-4.0-dev build-essential libgtk-3-dev libappindicator3-dev patchelf patchelf fuse -qq -o Dpkg::Use-Pty=0
  - sh ./rustup-init.sh -y
  - source $HOME/.cargo/env
  - rustc --version
  - yarn install
  # - yarn audit
  - yarn tauri info
# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ee/ci/docker/using_docker_images.html#what-is-a-service
# services:
#   - mysql:latest
#   - redis:latest
#   - postgres:latest

# This folder is cached between builds
# https://docs.gitlab.com/ee/ci/yaml/index.html#cache
cache:
  paths:
    - node_modules/
    - /var/cache/apt/archives
build:
  script:
    - yarn build
  artifacts:
    untracked: false
    expire_in: 30 days
    public: true
    paths:
      - "*"
