# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Nodejs.gitlab-ci.yml

# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

# This folder is cached between builds
# https://docs.gitlab.com/ee/ci/yaml/index.html#cache
cache:
  paths:
    - .apt
    - node_modules/
    - packages/src-renderer/node_modules/
    - packages/src-tauri/node_modules/
    - packages/src-tauri/target
    # - apt-cache/

before_script:
  - rm -f /etc/apt/apt.conf.d/docker-clean
  - mkdir -p .apt && mkdir -p /var/cache/apt/archives && mount --bind .apt /var/cache/apt/archives/
  - export DEBIAN_FRONTEND="noninteractive"
  - export VERSION="0.0.1"
  #  -o dir::cache::archives="apt-cache"
  - apt-get -yqq -o Dpkg::Use-Pty=0 update
  - apt-get -yqq -o Dpkg::Use-Pty=0 install apt-utils
  - apt-get -yqq -o Dpkg::Use-Pty=0 upgrade
  # curl librsvg2-dev libssl-dev wget
  - apt-get -yqq -o Dpkg::Use-Pty=0 install libwebkit2gtk-4.0-dev build-essential libgtk-3-dev libappindicator3-dev patchelf patchelf fuse appstream
  - sh ./rustup-init.sh -y
  - source $HOME/.cargo/env
  - rustc --version
  - yarn install
  # - yarn audit
  - yarn tauri info
  - ls /var/cache/apt/ -la
# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ee/ci/docker/using_docker_images.html#what-is-a-service
# services:
#   - mysql:latest
#   - redis:latest
#   - postgres:latest

build:
  script:
    - yarn build
  artifacts:
    untracked: false
    expire_in: 30 days
    public: true
    paths:
      - "*"
      # - packages/src-tauri/target/release/bundle/deb/*
      # - packages/src-tauri/target/release/bundle/appimage/*

pages:
  stage: deploy
  script:
    - mkdir -p public
    - cp packages/src-renderer/dist public
  artifacts:
    paths:
      - public
